import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module"; 
import copy from "esbuild-plugin-copy";
import { sassPlugin } from 'esbuild-sass-plugin';
//import handlebars from 'handlebars';
//import fs from 'fs/promises';
//import path from 'path';
import { readFileSync } from "fs";

const handlebarsPlugin = {
  name: 'handlebars',
  setup(build) {
    build.onLoad({ filter: /\.hbs$/ }, async (args) => {
      const templateContent = readFileSync(args.path, 'utf8');
      return {
        contents: `import Handlebars from 'handlebars'; export default Handlebars.compile(${JSON.stringify(templateContent)});`,
        loader: 'js',
      };
    });
  },
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const outputDir = "dist"; // Cambiado de outfile a outdir

const obsidianExternals = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr"
];

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts", "src/styles/styles.scss"], // Incluye tu archivo SCSS como entrada
	bundle: true,
	external: [
		...obsidianExternals,
    ...builtinModules ],
	format: "cjs",
	target: "es2020", // Ajusta según tus necesidades
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: outputDir,
  entryNames: "[name]",
	minify: prod,
	loader: {
		'.svg': 'file', // Si usas SVG en tu proyecto
	},
	plugins: [handlebarsPlugin,
		sassPlugin({
			type: 'css', // Genera un archivo CSS
		}),
		copy({
			// Configuración del plugin
			resolveFrom: "cwd", // Usa la ruta relativa al directorio actual
			assets: [
				{
						from: "manifest.json", // Ruta de origen
						to: "dist/manifest.json", // Ruta de destino
				},
				{
					from: "dist/**/*",
					to: "C:/Users/elias/OneDrive/Obsidian/develop/.obsidian/plugins/obsidian-agenda",
				},
			],
		}),
	],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
