import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import copy from "esbuild-plugin-copy";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const outputFile = "dist/main.js";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: outputFile,
	minify: prod,
	plugins: [
		copy({
			// Configuración del plugin
			resolveFrom: "cwd", // Usa la ruta relativa al directorio actual
			assets: [
				{
						from: "src/views/templates/**/*", // Ruta de origen
						to: "dist/templates", // Ruta de destino
				},
				{
					from: "src/locales/**/*", // Ruta de origen
					to: "dist/locales", // Ruta de destino
				},
				{
						from: "src/styles/**/*", // Ruta de origen
						to: "dist/styles", // Ruta de destino
				},
				{
						from: "manifest.json", // Ruta de origen
						to: "dist/manifest.json", // Ruta de destino
				},
				{
					from: "dist/**/*",
					to: "C:/Users/elias/OneDrive/Documents/OneDrive/Obsidian/develop/.obsidian/plugins/obsidian-agenda",
				},
			],
		}),
	],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
